CREATE TABLE item (item_id INT PRIMARY KEY AUTO_INCREMENT,item_name VARCHAR(256) NOT NULL,item_price  INT NOT NULL,category_id INT);
INSERT INTO item VALUES (1,'堅牢な机',3000,1);
INSERT INTO item VALUES (2,'生焼け肉',50,2);
INSERT INTO item VALUES (3,'すっきりわかるJava入門',3000,3);
INSERT INTO item VALUES (4,'おしゃれな椅子',2000,1);
INSERT INTO item VALUES (5,'こんがり肉',500,2);
INSERT INTO item VALUES (6,'書き方ドリルSQL',2500,3);
INSERT INTO item VALUES (7,'ふわふわのベッド',30000,1);
INSERT INTO item VALUES (8,'ミラノ風ドリア',300,2);
SELECT item_name,item_price FROM item WHERE item_price >= 1000; 